version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
      nodejs: 14
    commands:
      - pwd
      - export ANDROID_TOOLS_FILENAME="commandlinetools-linux-8512546_latest.zip"
      - wget https://dl.google.com/android/repository/$ANDROID_TOOLS_FILENAME -P ~ > /dev/null
      - unzip ~/$ANDROID_TOOLS_FILENAME -d ~ > /dev/null 2>&1
      - mkdir -p /usr/local/android-sdk-linux/cmdline-tools
      - mv ~/cmdline-tools /usr/local/android-sdk-linux/cmdline-tools/latest
      - export PATH=$PATH:/usr/local/android-sdk-linux/cmdline-tools/latest:/usr/local/android-sdk-linux/cmdline-tools/latest/bin:/usr/local/android-sdk-linux/platform-tools
      - export ANDROID_SDK_ROOT=/usr/local/android-sdk-linux
      - yes | sdkmanager --licenses > /dev/null
      - sdkmanager "platform-tools" "platforms;android-31" > /dev/null
      - sdkmanager "build-tools;31.0.0" > /dev/null
  pre_build:
    commands:
      - echo Pre Build started on `date`
      - npm --version
      - npm install
      - cd android
      - pwd
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleRelease
      - ./gradlew generatePomFileForAarPublication
      - ./gradlew moveAAR
      - ./gradlew movePOM
