version: 0.2

phases:
  install:
    runtime-versions:
      apache: java
  pre_build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
artifacts:
  files:
     - './android/app/build/outputs/**/*.apk'